/**
 * The realtime contract for evaluation progress.
 *
 * `POST /api/evaluations` runs for 30–120s and answers only once, at the end.
 * These events are how the client learns what it is waiting on in the meantime.
 * They are strictly informational: the HTTP response remains the only source of
 * truth for whether the evaluation succeeded and what it produced.
 */

/** Client -> server: "tell me about this upload." Payload is the uploadId. */
export const EVALUATION_WATCH_EVENT = 'evaluation:watch';

/** Server -> client: the stage the pipeline has just entered. */
export const EVALUATION_PROGRESS_EVENT = 'evaluation:progress';

/**
 * The stages of the pipeline, in the order they run.
 *
 * A stable key rather than the words shown on screen: the display copy belongs
 * to the frontend, which is the only side that renders anything.
 *
 * Be aware that `mapping` is synchronous, in-memory work that completes in
 * milliseconds — it is emitted for completeness, but a client should not expect
 * it to be visible for any meaningful length of time.
 */
export type EvaluationPhase = 'ocr' | 'transform' | 'mapping' | 'marking';

export interface EvaluationProgress {
  /**
   * Echoed back so a client can ignore anything not its own.
   *
   * The id is generated by the client before it uploads, not by the server:
   * the server has nothing to hand out until the request it would name is
   * already finished.
   */
  uploadId: string;
  phase: EvaluationPhase;
}

/**
 * Shape an upload id must have to be accepted.
 *
 * The id becomes part of a room name, so it is checked rather than trusted.
 * A UUID is what the client generates; anything else is ignored, and the
 * upload simply proceeds without progress.
 */
export const UPLOAD_ID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isValidUploadId(value: unknown): value is string {
  return typeof value === 'string' && UPLOAD_ID_PATTERN.test(value);
}
